## Introducción a PyTorch

PyTorch es un framework de aprendizaje profundo desarrollado por Facebook, de **código abierto** y con contribuciones de miles de usuarios. Es una alternativa a otros frameworks como TensorFlow o MXNet. El lenguaje de programación utilizado por este framework es Python (aunque muchas de sus partes están programas en otros lenguajes como C++). En este tutorial, vamos a aprender los fundamentos de PyTorch para que puedas utilizarlo en el resto de prácticas.



#### Primeros pasos
Lo primero consiste en ver si tenemos PyTorch instalado y conocer su versión:

In [2]:
import torch
print(torch.__version__)

2.0.1+cpu


si en la salida anterior ves **cpu** será que estás ejecutando una compilación de PyTorch solo con soporte para CPU y no GPU. Si por el contrario quieres ejecutar PyTorch en una máquina con GPU como Google Colab (o incluso tu propia máquina con GPU y Cuda instalado), la salida de este comando debería indicartelo.

Un aspecto importante en los experimentos que hagamos será la reproducibilidad de resultados. Establecemos una semilla para que todos los números aleatorios generados sean los mismos ejecución tras ejecución:

In [5]:
torch.manual_seed(2032)

#### Tensores

Los tensores son la pieza clave en cualquier framework de aprendizaje profundo. Son equivalentes a los arrays de Numpy pero tienen ciertas diferencias muy importantes:

1. Los tensores **pueden moverse entre diferentes dispositivos**. Es decir, podemos tener un tensor en CPU y moverlo a la GPU y todos los cálculos realizados con este pasarán a realizarse en este dispositivo.
2. Los tensores están preparados para diferenciar sobre ellos (calcular las derivadas parciales necesarias para aplicar descenso de gradiente). 

De todas maneras, una de las principales ventajas de PyTorch es que si sabemos operar con arrays de Numpy, cambiar a hacerlo con tensores será muy sencillo. Vamos a crear nuestro primer Tensor:

In [9]:
x = torch.Tensor(3, 4)
print(x)

tensor([[-4.5760e+33,  4.5699e-41,  8.6083e+36,  3.0936e-41],
        [ 1.4013e-45,  0.0000e+00,  0.0000e+00,  4.5699e-41],
        [-5.5531e-11,  4.5699e-41,  1.8077e-43,  0.0000e+00]])


aquí tenemos un tensor de 3x4 de números reales, inicializado alteatoriamente. Podemos mostrar su dimensión:

In [10]:
print(x.shape)

torch.Size([3, 4])


También es posible inicializar tensores con otros valores, como por ejemplo, ceros o unos:

In [12]:
print(torch.zeros(3,4))
print(torch.ones(3,4))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


Otra manera de crear un tensor es hacerlo desde un array de numpy existente:

In [16]:
import numpy as np
np_arr = np.array([[1, 2], [3, 4]])
tensor = torch.from_numpy(np_arr)
print(tensor)
print(tensor.shape)

tensor([[1, 2],
        [3, 4]])
torch.Size([2, 2])


En este case se pude ver que como el array era de números enteros, el tensor resultante mantiene este tipo. Siempre podemos ver el **tipo de los elementos de un tensor** con la siguiente instrucción:

In [18]:
print(tensor.dtype)

torch.int64


Ten en cuenta que **el tipo es crítico** ya que nuestra red va a requerir muchísimos parámetros que al final van a ser tensores y la memoria de nuestros dispositivos es limitada. Te recomiendo el siguiente [enlace](https://pytorch.org/docs/stable/tensors.html) para conocer los diferentes tipos y saber cuando ocupa cada uno en memoria.

Además de crear tensores, muchas veces es interesante convertirlos de vuelta a Numpy. Podemos hacerlo de la siguiente manera:

In [19]:
tensor.cpu().numpy()

array([[1, 2],
       [3, 4]])

Ten en cuenta que la llamada cpu() lo que hace es mover el tensor a la cpu (si no está ya). Es importante hacer esta llamada porque para pasar el tensor a numpy tiene que estar en cpu primero.

Para mover tensores de un dispositivo a otro podemos hacerlo de la siguiente manera.

In [22]:
device = torch.device('cuda:0')
tensor.to(device)

AssertionError: Torch not compiled with CUDA enabled

obviamente para que esto funcione debemos tener PyTorch instalado con soporte para cuda. En este caso **cuda:0** indica que queremos mover el tensor a la primera GPU del sistema.

#### Operaciones con tensores

Existen multitud de operaciones que se pueden realizar con tensores. Aquí vamos a describir las más básicas. En el siguiente [enlace](https://pytorch.org/docs/stable/tensors.html#) tienes una descripción completa de todas las operaciones que se pueden realizar.